version: '3.7'

services:
  web:
    build: .
    command: python manage.py collectstatic --no-input && gunicorn --workers=2 npl_app.wsgi -b 0.0.0.0:8000
    env_file:
      - .env
    volumes:
      - .:/code
    ports:
      - 8000:8000
    depends_on:
      - redis
  redis:
    image: 'redis:alpine'
    volumes:
      - redis_data:/data/
    command: --port 6379
    ports:
      - "6379:6379"

volumes:
  redis_data: