# Generated by Django 2.0.2 on 2018-03-30 20:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Encounter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('action_prayer', models.BooleanField(default=False)),
                ('action_testimony', models.BooleanField(default=False)),
                ('action_gospel', models.BooleanField(default=False)),
                ('phone_number', models.IntegerField(blank=True, null=True)),
                ('response', models.CharField(choices=[('RL', 'Red Light'), ('YL', 'Yellow Light'), ('GL', 'Green Light'), ('WT', 'Believer Wants Training'), ('RT', 'Believer Rejects Training')], max_length=2)),
                ('notes', models.TextField(blank=True)),
                ('date_time', models.DateTimeField(blank=True)),
                ('is_oikos', models.BooleanField(default=False)),
                ('street_address', models.CharField(max_length=50)),
                ('apt_or_unit', models.CharField(blank=True, max_length=15)),
                ('city', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=20)),
                ('zip', models.IntegerField()),
                ('lat', models.FloatField(blank=True, null=True)),
                ('lng', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Laborer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_name', models.CharField(max_length=40)),
                ('creation_date', models.DateField()),
                ('members', models.ManyToManyField(to='npl.Laborer')),
            ],
        ),
        migrations.AddField(
            model_name='encounter',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='npl.Laborer'),
        ),
    ]
