# Generated by Django 2.0.3 on 2018-03-24 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('npl', '0002_encounter'),
    ]

    operations = [
        migrations.AddField(
            model_name='npl',
            name='action_gospel',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='npl',
            name='action_prayer',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='npl',
            name='action_testimony',
            field=models.BooleanField(default=False),
        ),
    ]
