# Generated by Django 2.0.2 on 2018-03-30 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('npl', '0002_auto_20180330_1520'),
    ]

    operations = [
        migrations.AlterField(
            model_name='encounter',
            name='zip',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
