# Generated by Django 2.0.3 on 2018-03-27 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('npl', '0003_auto_20180324_1725'),
    ]

    operations = [
        migrations.AlterField(
            model_name='npl',
            name='notes',
            field=models.TextField(default='Notes...'),
        ),
    ]
