# Generated by Django 2.0.2 on 2018-03-30 21:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('npl', '0003_auto_20180330_1521'),
    ]

    operations = [
        migrations.RenameField(
            model_name='encounter',
            old_name='user',
            new_name='laborer',
        ),
    ]
