# Generated by Django 2.0.3 on 2018-03-28 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('npl', '0004_auto_20180327_1742'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_name', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=40)),
                ('email', models.CharField(max_length=50)),
                ('encrypted_password', models.CharField(max_length=150)),
                ('team_members', models.ManyToManyField(to='npl.Team')),
            ],
        ),
        migrations.AddField(
            model_name='npl',
            name='apt_or_unit',
            field=models.CharField(default='', max_length=15),
        ),
        migrations.AddField(
            model_name='npl',
            name='city',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='npl',
            name='is_oikos',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='npl',
            name='lat',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='npl',
            name='lng',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='npl',
            name='state',
            field=models.CharField(default='', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='npl',
            name='street_address',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='npl',
            name='zip',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
