# Generated by Django 2.0.3 on 2018-03-28 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('npl', '0005_auto_20180327_1913'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='date_created',
            field=models.DateField(default='2018-03-27'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='date_created',
            field=models.DateField(default='2018-03-27'),
            preserve_default=False,
        ),
    ]
