# Generated by Django 2.0.3 on 2018-04-07 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('npl', '0005_auto_20180330_1646'),
    ]

    operations = [
        migrations.AddField(
            model_name='encounter',
            name='response_description',
            field=models.CharField(max_length=40, null=True),
        ),
    ]
