# Generated by Django 2.0.3 on 2018-03-28 00:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('npl', '0006_auto_20180327_1914'),
    ]

    operations = [
        migrations.RenameField(
            model_name='team',
            old_name='date_created',
            new_name='date_team_created',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='date_created',
            new_name='date_account_created',
        ),
    ]
