# Generated by Django 2.0.3 on 2018-04-07 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('npl', '0006_encounter_response_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='encounter',
            name='full_address',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
