# Generated by Django 2.0.3 on 2018-04-26 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('npl', '0007_encounter_full_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='creation_date',
            field=models.DateTimeField(blank=True),
        ),
    ]
