# Generated by Django 2.0.3 on 2018-04-27 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('npl', '0008_auto_20180426_1808'),
    ]

    operations = [
        migrations.AlterField(
            model_name='laborer',
            name='creation_date',
            field=models.DateTimeField(),
        ),
    ]
