# Generated by Django 2.0.3 on 2018-07-03 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('npl', '0009_auto_20180427_1711'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='number_of_members',
            field=models.IntegerField(default=1),
        ),
    ]
