# Generated by Django 2.0.3 on 2018-07-27 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('npl', '0010_team_number_of_members'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='creation_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
